#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.dirname(__file__)+'/modules')

if __name__ == "__main__": 
  if len(sys.argv)>1 and sys.argv[1] == "serve":
    from cronograph import server
    server.serve()
  else:
    from cronograph import cron
    cron.handle()
