#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.dirname(__file__)+'/modules')
from cronograph import server, cron

def banner():
  print "cronograph - Collect, view and analyze cronjob execution logs"  
  print
  print "cronograph [path-to-sqlite3-database] <cronjob>"
  print "    Log execution of given <cronjob>"
  print
  print "cronograph serve [path-to-sqlite3-database] [port]"
  print "    Start server on given port (default is 8080)"
  print
  print "Default database file used is ~/.cronograph.sqlite3"
  print
  print "Example crontab entry:"
  print
  print "0 0 * * * /home/user/bin/cronograph rsnapshot daily"
  exit(1)

if __name__ == "__main__": 
  if len(sys.argv)>1 and sys.argv[1] == "serve":
    server.serve()
  else:
    cron.handle()
